// Firebase removed — app is Supabase-only. This stub prevents import errors during migration.
export const storage: any = null;
export const db: any = null;
export const auth: any = null;
export const storageRef: any = () => {};
export const uploadBytesResumable: any = () => {};
export const getDownloadURL: any = async () => '';
export const deleteObject: any = async () => {};
export const doc: any = () => {};
export const collection: any = () => {};
export const getDoc: any = async () => ({ exists: () => false });
export const getDocs: any = async () => ({ empty: true, docs: [] });
export const setDoc: any = async () => {};
export const updateDoc: any = async () => {};
export const addDoc: any = async () => ({ id: 'stub' });
export const deleteDoc: any = async () => {};
export const onSnapshot: any = () => () => {};
export const query: any = () => {};
export const where: any = () => {};
export const orderBy: any = () => {};
export const limit: any = () => {};
export const serverTimestamp: any = () => Date.now();
export const Timestamp: any = { now: () => ({ toDate: () => new Date() }) };
export const runTransaction: any = async () => {};
export const writeBatch: any = () => ({ set: () => {}, update: () => {}, delete: () => {}, commit: async () => {} });
export const ensureFirebaseAuth: any = async () => null;
export const FIRESTORE_COLLECTIONS: any = {};
export default null as any;
